# Generated by Django 4.1.5 on 2023-02-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('refrigerated', 'refrigerated'), ('frozen', 'frozen')], max_length=16, null=True),
        ),
    ]
