# Generated by Django 4.1.6 on 2023-02-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0003_item_barcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='status',
            new_name='location',
        ),
        migrations.AddField(
            model_name='item',
            name='amount',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
